export interface ICountry { name: string; isoCode: string; }
export interface IState  { name: string; isoCode: string; countryCode: string; }

export const COUNTRIES: ICountry[] = [
  { name: "Afghanistan", isoCode: "AF" },
  { name: "Albania", isoCode: "AL" },
  { name: "Algeria", isoCode: "DZ" },
  { name: "Andorra", isoCode: "AD" },
  { name: "Angola", isoCode: "AO" },
  { name: "Antigua and Barbuda", isoCode: "AG" },
  { name: "Argentina", isoCode: "AR" },
  { name: "Armenia", isoCode: "AM" },
  { name: "Australia", isoCode: "AU" },
  { name: "Austria", isoCode: "AT" },
  { name: "Azerbaijan", isoCode: "AZ" },
  { name: "Bahamas", isoCode: "BS" },
  { name: "Bahrain", isoCode: "BH" },
  { name: "Bangladesh", isoCode: "BD" },
  { name: "Barbados", isoCode: "BB" },
  { name: "Belarus", isoCode: "BY" },
  { name: "Belgium", isoCode: "BE" },
  { name: "Belize", isoCode: "BZ" },
  { name: "Benin", isoCode: "BJ" },
  { name: "Bhutan", isoCode: "BT" },
  { name: "Bolivia", isoCode: "BO" },
  { name: "Bosnia and Herzegovina", isoCode: "BA" },
  { name: "Botswana", isoCode: "BW" },
  { name: "Brazil", isoCode: "BR" },
  { name: "Brunei", isoCode: "BN" },
  { name: "Bulgaria", isoCode: "BG" },
  { name: "Burkina Faso", isoCode: "BF" },
  { name: "Burundi", isoCode: "BI" },
  { name: "Cabo Verde", isoCode: "CV" },
  { name: "Cambodia", isoCode: "KH" },
  { name: "Cameroon", isoCode: "CM" },
  { name: "Canada", isoCode: "CA" },
  { name: "Central African Republic", isoCode: "CF" },
  { name: "Chad", isoCode: "TD" },
  { name: "Chile", isoCode: "CL" },
  { name: "China", isoCode: "CN" },
  { name: "Colombia", isoCode: "CO" },
  { name: "Comoros", isoCode: "KM" },
  { name: "Congo (Brazzaville)", isoCode: "CG" },
  { name: "Congo (Kinshasa)", isoCode: "CD" },
  { name: "Costa Rica", isoCode: "CR" },
  { name: "Croatia", isoCode: "HR" },
  { name: "Cuba", isoCode: "CU" },
  { name: "Cyprus", isoCode: "CY" },
  { name: "Czech Republic", isoCode: "CZ" },
  { name: "Denmark", isoCode: "DK" },
  { name: "Djibouti", isoCode: "DJ" },
  { name: "Dominica", isoCode: "DM" },
  { name: "Dominican Republic", isoCode: "DO" },
  { name: "Ecuador", isoCode: "EC" },
  { name: "Egypt", isoCode: "EG" },
  { name: "El Salvador", isoCode: "SV" },
  { name: "Equatorial Guinea", isoCode: "GQ" },
  { name: "Eritrea", isoCode: "ER" },
  { name: "Estonia", isoCode: "EE" },
  { name: "Eswatini", isoCode: "SZ" },
  { name: "Ethiopia", isoCode: "ET" },
  { name: "Fiji", isoCode: "FJ" },
  { name: "Finland", isoCode: "FI" },
  { name: "France", isoCode: "FR" },
  { name: "Gabon", isoCode: "GA" },
  { name: "Gambia", isoCode: "GM" },
  { name: "Georgia", isoCode: "GE" },
  { name: "Germany", isoCode: "DE" },
  { name: "Ghana", isoCode: "GH" },
  { name: "Greece", isoCode: "GR" },
  { name: "Grenada", isoCode: "GD" },
  { name: "Guatemala", isoCode: "GT" },
  { name: "Guinea", isoCode: "GN" },
  { name: "Guinea-Bissau", isoCode: "GW" },
  { name: "Guyana", isoCode: "GY" },
  { name: "Haiti", isoCode: "HT" },
  { name: "Honduras", isoCode: "HN" },
  { name: "Hungary", isoCode: "HU" },
  { name: "Iceland", isoCode: "IS" },
  { name: "India", isoCode: "IN" },
  { name: "Indonesia", isoCode: "ID" },
  { name: "Iran", isoCode: "IR" },
  { name: "Iraq", isoCode: "IQ" },
  { name: "Ireland", isoCode: "IE" },
  { name: "Israel", isoCode: "IL" },
  { name: "Italy", isoCode: "IT" },
  { name: "Jamaica", isoCode: "JM" },
  { name: "Japan", isoCode: "JP" },
  { name: "Jordan", isoCode: "JO" },
  { name: "Kazakhstan", isoCode: "KZ" },
  { name: "Kenya", isoCode: "KE" },
  { name: "Kiribati", isoCode: "KI" },
  { name: "Kuwait", isoCode: "KW" },
  { name: "Kyrgyzstan", isoCode: "KG" },
  { name: "Laos", isoCode: "LA" },
  { name: "Latvia", isoCode: "LV" },
  { name: "Lebanon", isoCode: "LB" },
  { name: "Lesotho", isoCode: "LS" },
  { name: "Liberia", isoCode: "LR" },
  { name: "Libya", isoCode: "LY" },
  { name: "Liechtenstein", isoCode: "LI" },
  { name: "Lithuania", isoCode: "LT" },
  { name: "Luxembourg", isoCode: "LU" },
  { name: "Madagascar", isoCode: "MG" },
  { name: "Malawi", isoCode: "MW" },
  { name: "Malaysia", isoCode: "MY" },
  { name: "Maldives", isoCode: "MV" },
  { name: "Mali", isoCode: "ML" },
  { name: "Malta", isoCode: "MT" },
  { name: "Marshall Islands", isoCode: "MH" },
  { name: "Mauritania", isoCode: "MR" },
  { name: "Mauritius", isoCode: "MU" },
  { name: "Mexico", isoCode: "MX" },
  { name: "Micronesia", isoCode: "FM" },
  { name: "Moldova", isoCode: "MD" },
  { name: "Monaco", isoCode: "MC" },
  { name: "Mongolia", isoCode: "MN" },
  { name: "Montenegro", isoCode: "ME" },
  { name: "Morocco", isoCode: "MA" },
  { name: "Mozambique", isoCode: "MZ" },
  { name: "Myanmar", isoCode: "MM" },
  { name: "Namibia", isoCode: "NA" },
  { name: "Nauru", isoCode: "NR" },
  { name: "Nepal", isoCode: "NP" },
  { name: "Netherlands", isoCode: "NL" },
  { name: "New Zealand", isoCode: "NZ" },
  { name: "Nicaragua", isoCode: "NI" },
  { name: "Niger", isoCode: "NE" },
  { name: "Nigeria", isoCode: "NG" },
  { name: "North Korea", isoCode: "KP" },
  { name: "North Macedonia", isoCode: "MK" },
  { name: "Norway", isoCode: "NO" },
  { name: "Oman", isoCode: "OM" },
  { name: "Pakistan", isoCode: "PK" },
  { name: "Palau", isoCode: "PW" },
  { name: "Palestine", isoCode: "PS" },
  { name: "Panama", isoCode: "PA" },
  { name: "Papua New Guinea", isoCode: "PG" },
  { name: "Paraguay", isoCode: "PY" },
  { name: "Peru", isoCode: "PE" },
  { name: "Philippines", isoCode: "PH" },
  { name: "Poland", isoCode: "PL" },
  { name: "Portugal", isoCode: "PT" },
  { name: "Qatar", isoCode: "QA" },
  { name: "Romania", isoCode: "RO" },
  { name: "Russia", isoCode: "RU" },
  { name: "Rwanda", isoCode: "RW" },
  { name: "Saint Kitts and Nevis", isoCode: "KN" },
  { name: "Saint Lucia", isoCode: "LC" },
  { name: "Saint Vincent and the Grenadines", isoCode: "VC" },
  { name: "Samoa", isoCode: "WS" },
  { name: "San Marino", isoCode: "SM" },
  { name: "Sao Tome and Principe", isoCode: "ST" },
  { name: "Saudi Arabia", isoCode: "SA" },
  { name: "Senegal", isoCode: "SN" },
  { name: "Serbia", isoCode: "RS" },
  { name: "Seychelles", isoCode: "SC" },
  { name: "Sierra Leone", isoCode: "SL" },
  { name: "Singapore", isoCode: "SG" },
  { name: "Slovakia", isoCode: "SK" },
  { name: "Slovenia", isoCode: "SI" },
  { name: "Solomon Islands", isoCode: "SB" },
  { name: "Somalia", isoCode: "SO" },
  { name: "South Africa", isoCode: "ZA" },
  { name: "South Korea", isoCode: "KR" },
  { name: "South Sudan", isoCode: "SS" },
  { name: "Spain", isoCode: "ES" },
  { name: "Sri Lanka", isoCode: "LK" },
  { name: "Sudan", isoCode: "SD" },
  { name: "Suriname", isoCode: "SR" },
  { name: "Sweden", isoCode: "SE" },
  { name: "Switzerland", isoCode: "CH" },
  { name: "Syria", isoCode: "SY" },
  { name: "Taiwan", isoCode: "TW" },
  { name: "Tajikistan", isoCode: "TJ" },
  { name: "Tanzania", isoCode: "TZ" },
  { name: "Thailand", isoCode: "TH" },
  { name: "Timor-Leste", isoCode: "TL" },
  { name: "Togo", isoCode: "TG" },
  { name: "Tonga", isoCode: "TO" },
  { name: "Trinidad and Tobago", isoCode: "TT" },
  { name: "Tunisia", isoCode: "TN" },
  { name: "Turkey", isoCode: "TR" },
  { name: "Turkmenistan", isoCode: "TM" },
  { name: "Tuvalu", isoCode: "TV" },
  { name: "Uganda", isoCode: "UG" },
  { name: "Ukraine", isoCode: "UA" },
  { name: "United Arab Emirates", isoCode: "AE" },
  { name: "United Kingdom", isoCode: "GB" },
  { name: "United States", isoCode: "US" },
  { name: "Uruguay", isoCode: "UY" },
  { name: "Uzbekistan", isoCode: "UZ" },
  { name: "Vanuatu", isoCode: "VU" },
  { name: "Vatican City", isoCode: "VA" },
  { name: "Venezuela", isoCode: "VE" },
  { name: "Vietnam", isoCode: "VN" },
  { name: "Yemen", isoCode: "YE" },
  { name: "Zambia", isoCode: "ZM" },
  { name: "Zimbabwe", isoCode: "ZW" },
];

// States/provinces for countries that have them
const STATES_MAP: Record<string, { name: string; isoCode: string }[]> = {
  US: [
    { name: "Alabama", isoCode: "AL" }, { name: "Alaska", isoCode: "AK" },
    { name: "Arizona", isoCode: "AZ" }, { name: "Arkansas", isoCode: "AR" },
    { name: "California", isoCode: "CA" }, { name: "Colorado", isoCode: "CO" },
    { name: "Connecticut", isoCode: "CT" }, { name: "Delaware", isoCode: "DE" },
    { name: "Florida", isoCode: "FL" }, { name: "Georgia", isoCode: "GA" },
    { name: "Hawaii", isoCode: "HI" }, { name: "Idaho", isoCode: "ID" },
    { name: "Illinois", isoCode: "IL" }, { name: "Indiana", isoCode: "IN" },
    { name: "Iowa", isoCode: "IA" }, { name: "Kansas", isoCode: "KS" },
    { name: "Kentucky", isoCode: "KY" }, { name: "Louisiana", isoCode: "LA" },
    { name: "Maine", isoCode: "ME" }, { name: "Maryland", isoCode: "MD" },
    { name: "Massachusetts", isoCode: "MA" }, { name: "Michigan", isoCode: "MI" },
    { name: "Minnesota", isoCode: "MN" }, { name: "Mississippi", isoCode: "MS" },
    { name: "Missouri", isoCode: "MO" }, { name: "Montana", isoCode: "MT" },
    { name: "Nebraska", isoCode: "NE" }, { name: "Nevada", isoCode: "NV" },
    { name: "New Hampshire", isoCode: "NH" }, { name: "New Jersey", isoCode: "NJ" },
    { name: "New Mexico", isoCode: "NM" }, { name: "New York", isoCode: "NY" },
    { name: "North Carolina", isoCode: "NC" }, { name: "North Dakota", isoCode: "ND" },
    { name: "Ohio", isoCode: "OH" }, { name: "Oklahoma", isoCode: "OK" },
    { name: "Oregon", isoCode: "OR" }, { name: "Pennsylvania", isoCode: "PA" },
    { name: "Rhode Island", isoCode: "RI" }, { name: "South Carolina", isoCode: "SC" },
    { name: "South Dakota", isoCode: "SD" }, { name: "Tennessee", isoCode: "TN" },
    { name: "Texas", isoCode: "TX" }, { name: "Utah", isoCode: "UT" },
    { name: "Vermont", isoCode: "VT" }, { name: "Virginia", isoCode: "VA" },
    { name: "Washington", isoCode: "WA" }, { name: "West Virginia", isoCode: "WV" },
    { name: "Wisconsin", isoCode: "WI" }, { name: "Wyoming", isoCode: "WY" },
    { name: "District of Columbia", isoCode: "DC" },
  ],
  CA: [
    { name: "Alberta", isoCode: "AB" }, { name: "British Columbia", isoCode: "BC" },
    { name: "Manitoba", isoCode: "MB" }, { name: "New Brunswick", isoCode: "NB" },
    { name: "Newfoundland and Labrador", isoCode: "NL" }, { name: "Northwest Territories", isoCode: "NT" },
    { name: "Nova Scotia", isoCode: "NS" }, { name: "Nunavut", isoCode: "NU" },
    { name: "Ontario", isoCode: "ON" }, { name: "Prince Edward Island", isoCode: "PE" },
    { name: "Quebec", isoCode: "QC" }, { name: "Saskatchewan", isoCode: "SK" },
    { name: "Yukon", isoCode: "YT" },
  ],
  GB: [
    { name: "England", isoCode: "ENG" }, { name: "Northern Ireland", isoCode: "NIR" },
    { name: "Scotland", isoCode: "SCT" }, { name: "Wales", isoCode: "WLS" },
  ],
  NG: [
    { name: "Abia", isoCode: "AB" }, { name: "Adamawa", isoCode: "AD" },
    { name: "Akwa Ibom", isoCode: "AK" }, { name: "Anambra", isoCode: "AN" },
    { name: "Bauchi", isoCode: "BA" }, { name: "Bayelsa", isoCode: "BY" },
    { name: "Benue", isoCode: "BE" }, { name: "Borno", isoCode: "BO" },
    { name: "Cross River", isoCode: "CR" }, { name: "Delta", isoCode: "DE" },
    { name: "Ebonyi", isoCode: "EB" }, { name: "Edo", isoCode: "ED" },
    { name: "Ekiti", isoCode: "EK" }, { name: "Enugu", isoCode: "EN" },
    { name: "FCT - Abuja", isoCode: "FC" }, { name: "Gombe", isoCode: "GO" },
    { name: "Imo", isoCode: "IM" }, { name: "Jigawa", isoCode: "JI" },
    { name: "Kaduna", isoCode: "KD" }, { name: "Kano", isoCode: "KN" },
    { name: "Katsina", isoCode: "KT" }, { name: "Kebbi", isoCode: "KE" },
    { name: "Kogi", isoCode: "KO" }, { name: "Kwara", isoCode: "KW" },
    { name: "Lagos", isoCode: "LA" }, { name: "Nasarawa", isoCode: "NA" },
    { name: "Niger", isoCode: "NI" }, { name: "Ogun", isoCode: "OG" },
    { name: "Ondo", isoCode: "ON" }, { name: "Osun", isoCode: "OS" },
    { name: "Oyo", isoCode: "OY" }, { name: "Plateau", isoCode: "PL" },
    { name: "Rivers", isoCode: "RI" }, { name: "Sokoto", isoCode: "SO" },
    { name: "Taraba", isoCode: "TA" }, { name: "Yobe", isoCode: "YO" },
    { name: "Zamfara", isoCode: "ZA" },
  ],
  AU: [
    { name: "Australian Capital Territory", isoCode: "ACT" },
    { name: "New South Wales", isoCode: "NSW" },
    { name: "Northern Territory", isoCode: "NT" },
    { name: "Queensland", isoCode: "QLD" },
    { name: "South Australia", isoCode: "SA" },
    { name: "Tasmania", isoCode: "TAS" },
    { name: "Victoria", isoCode: "VIC" },
    { name: "Western Australia", isoCode: "WA" },
  ],
  IN: [
    { name: "Andhra Pradesh", isoCode: "AP" }, { name: "Arunachal Pradesh", isoCode: "AR" },
    { name: "Assam", isoCode: "AS" }, { name: "Bihar", isoCode: "BR" },
    { name: "Chhattisgarh", isoCode: "CT" }, { name: "Goa", isoCode: "GA" },
    { name: "Gujarat", isoCode: "GJ" }, { name: "Haryana", isoCode: "HR" },
    { name: "Himachal Pradesh", isoCode: "HP" }, { name: "Jharkhand", isoCode: "JH" },
    { name: "Karnataka", isoCode: "KA" }, { name: "Kerala", isoCode: "KL" },
    { name: "Madhya Pradesh", isoCode: "MP" }, { name: "Maharashtra", isoCode: "MH" },
    { name: "Manipur", isoCode: "MN" }, { name: "Meghalaya", isoCode: "ML" },
    { name: "Mizoram", isoCode: "MZ" }, { name: "Nagaland", isoCode: "NL" },
    { name: "Odisha", isoCode: "OD" }, { name: "Punjab", isoCode: "PB" },
    { name: "Rajasthan", isoCode: "RJ" }, { name: "Sikkim", isoCode: "SK" },
    { name: "Tamil Nadu", isoCode: "TN" }, { name: "Telangana", isoCode: "TG" },
    { name: "Tripura", isoCode: "TR" }, { name: "Uttar Pradesh", isoCode: "UP" },
    { name: "Uttarakhand", isoCode: "UT" }, { name: "West Bengal", isoCode: "WB" },
    { name: "Delhi", isoCode: "DL" }, { name: "Jammu and Kashmir", isoCode: "JK" },
    { name: "Ladakh", isoCode: "LA" },
  ],
  BR: [
    { name: "Acre", isoCode: "AC" }, { name: "Alagoas", isoCode: "AL" },
    { name: "Amapá", isoCode: "AP" }, { name: "Amazonas", isoCode: "AM" },
    { name: "Bahia", isoCode: "BA" }, { name: "Ceará", isoCode: "CE" },
    { name: "Distrito Federal", isoCode: "DF" }, { name: "Espírito Santo", isoCode: "ES" },
    { name: "Goiás", isoCode: "GO" }, { name: "Maranhão", isoCode: "MA" },
    { name: "Mato Grosso", isoCode: "MT" }, { name: "Mato Grosso do Sul", isoCode: "MS" },
    { name: "Minas Gerais", isoCode: "MG" }, { name: "Pará", isoCode: "PA" },
    { name: "Paraíba", isoCode: "PB" }, { name: "Paraná", isoCode: "PR" },
    { name: "Pernambuco", isoCode: "PE" }, { name: "Piauí", isoCode: "PI" },
    { name: "Rio de Janeiro", isoCode: "RJ" }, { name: "Rio Grande do Norte", isoCode: "RN" },
    { name: "Rio Grande do Sul", isoCode: "RS" }, { name: "Rondônia", isoCode: "RO" },
    { name: "Roraima", isoCode: "RR" }, { name: "Santa Catarina", isoCode: "SC" },
    { name: "São Paulo", isoCode: "SP" }, { name: "Sergipe", isoCode: "SE" },
    { name: "Tocantins", isoCode: "TO" },
  ],
  MX: [
    { name: "Aguascalientes", isoCode: "AGU" }, { name: "Baja California", isoCode: "BCN" },
    { name: "Baja California Sur", isoCode: "BCS" }, { name: "Campeche", isoCode: "CAM" },
    { name: "Chiapas", isoCode: "CHP" }, { name: "Chihuahua", isoCode: "CHH" },
    { name: "Ciudad de México", isoCode: "CMX" }, { name: "Coahuila", isoCode: "COA" },
    { name: "Colima", isoCode: "COL" }, { name: "Durango", isoCode: "DUR" },
    { name: "Guanajuato", isoCode: "GUA" }, { name: "Guerrero", isoCode: "GRO" },
    { name: "Hidalgo", isoCode: "HID" }, { name: "Jalisco", isoCode: "JAL" },
    { name: "México", isoCode: "MEX" }, { name: "Michoacán", isoCode: "MIC" },
    { name: "Morelos", isoCode: "MOR" }, { name: "Nayarit", isoCode: "NAY" },
    { name: "Nuevo León", isoCode: "NLE" }, { name: "Oaxaca", isoCode: "OAX" },
    { name: "Puebla", isoCode: "PUE" }, { name: "Querétaro", isoCode: "QUE" },
    { name: "Quintana Roo", isoCode: "ROO" }, { name: "San Luis Potosí", isoCode: "SLP" },
    { name: "Sinaloa", isoCode: "SIN" }, { name: "Sonora", isoCode: "SON" },
    { name: "Tabasco", isoCode: "TAB" }, { name: "Tamaulipas", isoCode: "TAM" },
    { name: "Tlaxcala", isoCode: "TLA" }, { name: "Veracruz", isoCode: "VER" },
    { name: "Yucatán", isoCode: "YUC" }, { name: "Zacatecas", isoCode: "ZAC" },
  ],
  ZA: [
    { name: "Eastern Cape", isoCode: "EC" }, { name: "Free State", isoCode: "FS" },
    { name: "Gauteng", isoCode: "GP" }, { name: "KwaZulu-Natal", isoCode: "KZN" },
    { name: "Limpopo", isoCode: "LP" }, { name: "Mpumalanga", isoCode: "MP" },
    { name: "Northern Cape", isoCode: "NC" }, { name: "North West", isoCode: "NW" },
    { name: "Western Cape", isoCode: "WC" },
  ],
  GH: [
    { name: "Ahafo", isoCode: "AF" }, { name: "Ashanti", isoCode: "AH" },
    { name: "Bono", isoCode: "BO" }, { name: "Bono East", isoCode: "BE" },
    { name: "Central", isoCode: "CP" }, { name: "Eastern", isoCode: "EP" },
    { name: "Greater Accra", isoCode: "AA" }, { name: "North East", isoCode: "NE" },
    { name: "Northern", isoCode: "NP" }, { name: "Oti", isoCode: "OT" },
    { name: "Savannah", isoCode: "SV" }, { name: "Upper East", isoCode: "UE" },
    { name: "Upper West", isoCode: "UW" }, { name: "Volta", isoCode: "TV" },
    { name: "Western", isoCode: "WP" }, { name: "Western North", isoCode: "WN" },
  ],
  KE: [
    { name: "Baringo", isoCode: "01" }, { name: "Bomet", isoCode: "02" },
    { name: "Bungoma", isoCode: "03" }, { name: "Busia", isoCode: "04" },
    { name: "Elgeyo-Marakwet", isoCode: "05" }, { name: "Embu", isoCode: "06" },
    { name: "Garissa", isoCode: "07" }, { name: "Homa Bay", isoCode: "08" },
    { name: "Isiolo", isoCode: "09" }, { name: "Kajiado", isoCode: "10" },
    { name: "Kakamega", isoCode: "11" }, { name: "Kericho", isoCode: "12" },
    { name: "Kiambu", isoCode: "13" }, { name: "Kilifi", isoCode: "14" },
    { name: "Kirinyaga", isoCode: "15" }, { name: "Kisii", isoCode: "16" },
    { name: "Kisumu", isoCode: "17" }, { name: "Kitui", isoCode: "18" },
    { name: "Kwale", isoCode: "19" }, { name: "Laikipia", isoCode: "20" },
    { name: "Lamu", isoCode: "21" }, { name: "Machakos", isoCode: "22" },
    { name: "Makueni", isoCode: "23" }, { name: "Mandera", isoCode: "24" },
    { name: "Marsabit", isoCode: "25" }, { name: "Meru", isoCode: "26" },
    { name: "Migori", isoCode: "27" }, { name: "Mombasa", isoCode: "28" },
    { name: "Murang'a", isoCode: "29" }, { name: "Nairobi", isoCode: "30" },
    { name: "Nakuru", isoCode: "31" }, { name: "Nandi", isoCode: "32" },
    { name: "Narok", isoCode: "33" }, { name: "Nyamira", isoCode: "34" },
    { name: "Nyandarua", isoCode: "35" }, { name: "Nyeri", isoCode: "36" },
    { name: "Samburu", isoCode: "37" }, { name: "Siaya", isoCode: "38" },
    { name: "Taita-Taveta", isoCode: "39" }, { name: "Tana River", isoCode: "40" },
    { name: "Tharaka-Nithi", isoCode: "41" }, { name: "Trans Nzoia", isoCode: "42" },
    { name: "Turkana", isoCode: "43" }, { name: "Uasin Gishu", isoCode: "44" },
    { name: "Vihiga", isoCode: "45" }, { name: "Wajir", isoCode: "46" },
    { name: "West Pokot", isoCode: "47" },
  ],
  DE: [
    { name: "Baden-Württemberg", isoCode: "BW" }, { name: "Bavaria", isoCode: "BY" },
    { name: "Berlin", isoCode: "BE" }, { name: "Brandenburg", isoCode: "BB" },
    { name: "Bremen", isoCode: "HB" }, { name: "Hamburg", isoCode: "HH" },
    { name: "Hesse", isoCode: "HE" }, { name: "Lower Saxony", isoCode: "NI" },
    { name: "Mecklenburg-Vorpommern", isoCode: "MV" }, { name: "North Rhine-Westphalia", isoCode: "NW" },
    { name: "Rhineland-Palatinate", isoCode: "RP" }, { name: "Saarland", isoCode: "SL" },
    { name: "Saxony", isoCode: "SN" }, { name: "Saxony-Anhalt", isoCode: "ST" },
    { name: "Schleswig-Holstein", isoCode: "SH" }, { name: "Thuringia", isoCode: "TH" },
  ],
  FR: [
    { name: "Auvergne-Rhône-Alpes", isoCode: "ARA" }, { name: "Bourgogne-Franche-Comté", isoCode: "BFC" },
    { name: "Bretagne", isoCode: "BRE" }, { name: "Centre-Val de Loire", isoCode: "CVL" },
    { name: "Corse", isoCode: "COR" }, { name: "Grand Est", isoCode: "GES" },
    { name: "Hauts-de-France", isoCode: "HDF" }, { name: "Île-de-France", isoCode: "IDF" },
    { name: "Normandie", isoCode: "NOR" }, { name: "Nouvelle-Aquitaine", isoCode: "NAQ" },
    { name: "Occitanie", isoCode: "OCC" }, { name: "Pays de la Loire", isoCode: "PDL" },
    { name: "Provence-Alpes-Côte d'Azur", isoCode: "PAC" },
  ],
  AE: [
    { name: "Abu Dhabi", isoCode: "AZ" }, { name: "Ajman", isoCode: "AJ" },
    { name: "Dubai", isoCode: "DU" }, { name: "Fujairah", isoCode: "FU" },
    { name: "Ras Al Khaimah", isoCode: "RK" }, { name: "Sharjah", isoCode: "SH" },
    { name: "Umm Al Quwain", isoCode: "UQ" },
  ],
  SA: [
    { name: "Riyadh", isoCode: "01" }, { name: "Mecca", isoCode: "02" },
    { name: "Medina", isoCode: "03" }, { name: "Eastern Province", isoCode: "04" },
    { name: "Asir", isoCode: "05" }, { name: "Tabuk", isoCode: "06" },
    { name: "Hail", isoCode: "07" }, { name: "Northern Borders", isoCode: "08" },
    { name: "Jizan", isoCode: "09" }, { name: "Najran", isoCode: "10" },
    { name: "Al Bahah", isoCode: "11" }, { name: "Al Jouf", isoCode: "12" },
    { name: "Qassim", isoCode: "14" },
  ],
  PK: [
    { name: "Punjab", isoCode: "PB" }, { name: "Sindh", isoCode: "SD" },
    { name: "Khyber Pakhtunkhwa", isoCode: "KP" }, { name: "Balochistan", isoCode: "BA" },
    { name: "Gilgit-Baltistan", isoCode: "GB" }, { name: "Azad Kashmir", isoCode: "AJK" },
    { name: "Islamabad Capital Territory", isoCode: "IS" },
  ],
  NZ: [
    { name: "Auckland", isoCode: "AUK" }, { name: "Bay of Plenty", isoCode: "BOP" },
    { name: "Canterbury", isoCode: "CAN" }, { name: "Gisborne", isoCode: "GIS" },
    { name: "Hawke's Bay", isoCode: "HKB" }, { name: "Manawatu-Whanganui", isoCode: "MWT" },
    { name: "Marlborough", isoCode: "MBH" }, { name: "Nelson", isoCode: "NSN" },
    { name: "Northland", isoCode: "NTL" }, { name: "Otago", isoCode: "OTA" },
    { name: "Southland", isoCode: "STL" }, { name: "Taranaki", isoCode: "TKI" },
    { name: "Tasman", isoCode: "TAS" }, { name: "Waikato", isoCode: "WKO" },
    { name: "Wellington", isoCode: "WGN" }, { name: "West Coast", isoCode: "WTC" },
  ],
};

export function getAllCountries(): ICountry[] {
  return COUNTRIES;
}

export function getStatesOfCountry(countryCode: string): IState[] {
  const states = STATES_MAP[countryCode];
  if (!states) return [];
  return states.map((s) => ({ ...s, countryCode }));
}
